//! Follow the Omarchy desktop theme.
//!
//! Omarchy publishes the active theme's palette at
//! `~/.local/state/omarchy/current/theme/colors.toml`. This module reads it,
//! reproduces Omarchy's own key-resolution cascade (see
//! `/usr/share/omarchy/bin/omarchy-theme-color`), and maps the result onto
//! [`crate::theme::Theme`].

use std::collections::HashMap;

/// Parse a `colors.toml` into a flat map of top-level string values.
///
/// Values are kept as strings rather than colours because not every value is
/// a colour: `mode` is a keyword, and some themes carry gradient specs like
/// `-45deg`. A document that does not parse yields an empty map -- the caller
/// then falls back to siggy's own default theme.
#[allow(dead_code)]
pub(crate) fn parse_colors(contents: &str) -> HashMap<String, String> {
    let table: toml::Table = match contents.parse() {
        Ok(t) => t,
        Err(e) => {
            crate::debug_log::logf(format_args!("omarchy colors.toml parse error: {e}"));
            return HashMap::new();
        }
    };
    table
        .into_iter()
        .filter_map(|(k, v)| match v {
            toml::Value::String(s) => Some((k, s)),
            toml::Value::Integer(_) | toml::Value::Float(_) | toml::Value::Boolean(_) => {
                Some((k, v.to_string()))
            }
            _ => None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_colors_reads_string_values() {
        let src = r##"
# Generated by Aether for Omarchy v4.
mode = "dark"
accent = "#ac6380"
background = "#000000"
"##;
        let map = parse_colors(src);
        assert_eq!(map.get("mode").map(String::as_str), Some("dark"));
        assert_eq!(map.get("accent").map(String::as_str), Some("#ac6380"));
        assert_eq!(map.get("background").map(String::as_str), Some("#000000"));
        assert_eq!(map.len(), 3);
    }

    #[test]
    fn parse_colors_ignores_tables_and_returns_empty_on_garbage() {
        let src = "accent = \"#ac6380\"\n[some_table]\nnested = \"x\"\n";
        let map = parse_colors(src);
        assert_eq!(map.get("accent").map(String::as_str), Some("#ac6380"));
        assert!(!map.contains_key("nested"));
        assert!(!map.contains_key("some_table"));

        assert!(parse_colors("this is not = = toml").is_empty());
    }
}
